### ISSUE TITLE
Weeping angels crashes game / server when activated inside TARDIS

### ISSUE THREAD

**Issue by dangerousones** [ReallySub/Weeping-Angels-Mod#162]
The game crashes after spawning / activating an angel inside a TARDIS, attached is the server crash report
[crash-2021-04-13_19.45.41-server.txt](https://github.com/WhoCraft/Weeping-Angels/files/6306337/crash-2021-04-13_19.45.41-server.txt)

**Comment by Jeryn99** [comment]
disable weeping angel compat features and wait on tardis mod 1.5

**Comment by 50ap5ud5** [comment]
As a side note, please remember to tell users on your server to disable the config option on their client, even if the server has it disabled.

This is because Weeping Angel's config uses a type of config called the Common Config which **does not** sync any of its config options from server to client.

@Suff99 Maybe we should consider moving syncable entries like these to the Server Config instead of the Common Config?
