### ISSUE TITLE
java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by PeanutBoy679** [ReallySub/Weeping-Angels-Mod#180]
i used /locate and,found a dalek ship,and sees daleks dropping outta the ship.when i tried to get close to it,my mc stops responding.and i was suggested to upload this on github so heres the crash report crash-2021-10-04_21.24.42-server.txt -> https://wklej.spigot.pl/#/GAAT7NyNA5F99O6yEqJTswdn0_RV9B0kAVQRQIWyHrb2SQ

**Comment by Jeryn99** [comment]
Hey there, I released a version of Angels that might fix this: https://www.curseforge.com/minecraft/mc-mods/weeping-angels-mod/files/3482212

I know the version you have installed is already 2.1.4, but I had to re-release it due to this issue

I'm going to close this, as I think I have solved it, but if you encounter it with this new build, please let me know
