### ISSUE TITLE
1.16.5 infinite teleporting

### ISSUE THREAD

**Issue by StrandedTimelord** [ReallySub/Weeping-Angels-Mod#257]
I installed the weeping angels mod in 1.16.5 with the new tardis mod, and a weeping angel snuck up behind me. I was able to kill it but was transported by something with the weeping angel effect. Every time I load into a new place from the weeping angel ability, I disappear and go somewhere else. There is no way to stop it that I know of. I might just have to delete the world and start over. I am unable to do anything anymore.

**Comment by Jeryn99** [comment]
1.16.5 is unbalanced due to porting issues around that time - it will be address once Regeneration is on Fabric this week
I am going to go through a massive backlog for 1.16.5 and fix a whole selection of things - in the meantime I recommend playing with the config to reduce these issues you're having until it is resolved.

If you are not comfortable editing config files, I recommend installing the mod ``configured``

**Comment by Jeryn99** [comment]
I now have time to address this - I will keep you updated
