### ISSUE TITLE
angels spawn parameters are not in config

### ISSUE THREAD

**Issue by YellowRockCo** [ReallySub/Weeping-Angels-Mod#268]
Minecraft 1.19.2 forge, weeping angels mod version 43.0.8 angels spawn parameters are not in the mod config. on top of this the angels are not spawning.

GitHub says I cant upload the config for the version as such I instead uploaded a screen shot of the config.
![image](https://user-images.githubusercontent.com/117548707/200147471-a6a99e97-50ae-424e-b5c3-cf72ee0b338a.png)

please alert me if this is working as intended or if I've messed up the report.

**Comment by Jeryn99** [comment]
Hello - the reason they do not appear in the config file for forge 1.19.2 is because they instead use Forges biome modifier system. You can read up on them here (https://forge.gemwire.uk/wiki/Biome_Modifiers#:~:text=Biome%20Modifiers%20are%20a%20data,spawns%20and%20mob%20spawn%20costs) 

You can change the spawns with a data pack :)
