### ISSUE TITLE
To many Weeping Angels I say!

### ISSUE THREAD

**Issue by BurgerPotato** [ReallySub/Weeping-Angels-Mod#316]
Me and my friends make neither portal, we go in the neither, we saw lots of weeping angels, we get teleported out of there into the overworld by them, my friend makes timey wimy detector, we go into the neither and quickly run and hide ourselves in a hole, it say more than 210 weeping angels are near us and are trying to get to us I can take a screen shot of this happening if people want proof. (1.20.1 is the version and the world is on hard mode)

**Comment by Jeryn99** [comment]
I will investigate this, it is because the Nether only consists of a few biomes while the overworld consists of many. This causes the nether to be flooded with angels, I will eventually be making a altered config file for spawns where the user can choose the settings per biome

**Comment by Pelargir42** [comment]
Hope these observations will help.

I have reduced the spawn rates in the config as much as possible. 

OverWorld and The Aether I rarely see them 

The Nether and Twilight Forest would be suicidal if not for the teleporting the player away bit. 

In the Twilight Forest, there does seem to be a biome aspect to how they spawn.  Not completely sure as I have yet to intentionally go to the Twilight forest, I was forced to build a portal just so I had a way back to the overworld.

The Nether I have yet to explore enough to see how the other biomes react.  

I would like them to be about as rare as Endermen, at least in the dimensions that are not The End, in the pack I'm throwing together.

**Comment by laurasharp** [comment]
Yeah this is a big issue. We can't even go in the neither as we are basically teleported out within 5 mins of being there. 

If there is anyway to get this fixed sooner than later that would be helpful as we have several other mods that require us to go to the Niether and because of this one mod we can't do those. 

Thank you and hope to see an update soon.

**Comment by ZiLenTz** [comment]
Would love to have this fix too.

Currently with 5% weight, it works properly in Overworld as the spawn rate is quite rare compared to default.
However, in Nether there are quite a lot of them and make it unplayable without disabling the angel entirely.

MC 1.20.1
Fabric 0.14.24

**Comment by pswearin** [comment]
the idea of this mod is amazing and I really enjoyed it at first but once we entered the Nether we quickly realized it breaks the nether because there are soooo many angles.  On top of this, the timey wimey detector is a really cool idea and I loved it at first but I quickly discovered it is way too sensitive.  I don't need to know about an angel that is too far away to get me.  The constant dinging when there isn't any real danger essentially makes the detector useless.  The sensitivity of the detector needs to be configurable and the nether spawn rate needs to be fixed. Also, as far as I can tell, it seems like the mod completely ignores spawn caps entirely as we changed the spawn category to axolotl thinking that may prevent spawns in the nether but ended up with over 700 angles in our loaded area in the overworld (and that's just with one player logged in)   So we're removing the mod.  We'll put it back if it ever gets fixed.

**Comment by ArtJiggy23** [comment]
also dealing with this, and i have better nether so there are more biomes but there are just so many angels i have not even tried to actually explore the nether, using 1.20.1 and tried editing the configs

**Comment by snowinmars** [comment]
~~I'm trying to use InControl! mod to temporary fix the issue. If I'll succeed, I'l update the comment.~~

UPD: well, seems a perfect workaround.

1. Install [InControl!](https://www.curseforge.com/minecraft/mc-mods/in-control)
2. Run game at least once to create its config file
3. According to [their wiki](https://www.mcjty.eu/docs/mods/control-mods/), forbid spawning weeping angels in dimensions, they don't work 

`.minecraft/config/incontrol/spawn.json`
```json
[
  {
    "dimension": "minecraft:the_nether",
    "mob": ["weeping_angels:weeping_angel"],
    "result": "deny"
  }
]
```

To know the id of the dimension in modern Minecraft, write in chat the command `/execute in ` - and chat will suggest correct ids.

**Comment by Lemonwump** [comment]
First time with mod, came into the nether, instantly LAN world cause.....
![2024-02-15_20 15 15](https://github.com/Suff99/Weeping-Angels/assets/141963631/b60ce207-aa48-4e3c-a309-6ef36aa81e6d)

**Comment by LowReso1ution** [comment]
Does anyone know if this issue will be fixed anytime soonish? I'm getting about 30 angels spawning every 10 seconds in the nether and its practically impossible to progress past that stage. I'm using Fabric 1.20.1 if that helps at all

**Comment by SaintSaka** [comment]
Hello. I'm Saka. I've made a code in the [InControl!](https://www.curseforge.com/minecraft/mc-mods/in-control) mod for fix the limit of Angels and spawn rate on Nether (I put it at the end too because I don't know if it's broken there). I hope it's working for you too, it's hard to test these things alone. I ask you to share code improvements if you find errors.

1. You need to install the [InControl!](https://www.curseforge.com/minecraft/mc-mods/in-control). 
2. Run the game for create the configs archives (spawner and spawn) in `.minecraft/config/incontrol/` or `minecraft/versions/versioname/config/incontrol/`
3. Copy and paste the following codes in their respectives archives :3.

(Sorry for the bad organization. I couldn't format the comment properly)

### spawner.json
[
  {
    "mob": ["weeping_angels:weeping_angel"],
    "persecond": 0.01,
    "attempts": 2,
    "amount": {
      "minimum": 1,
      "maximum": 4
    },
    "conditions": {
      "dimension": ["minecraft:the_nether","minecraft:the_end"],
      "mindist": 25,
      "maxdist": 80,
      "minheight": 15,
      "maxheight": 55,
      "maxthis": 4
    }
  }
]
### spawn.json
```[
  {
    "mob": "weeping_angels:weeping_angel",
    "dimension": ["minecraft:the_nether","minecraft:the_end"],
    "incontrol": "true",
    "result": "allow"
  },
  {
    "mob": "weeping_angels:weeping_angel",
    "mincount": {
      "amount": 4
      
    },
    "result": "deny"
  },
{
    "mob": "weeping_angels:weeping_angel",
    "dimension": ["minecraft:the_nether","minecraft:the_end"],
  "incontrol": "false",
    "result": "deny"
  },
  {
    "mob": "weeping_angels:weeping_angel",
    "dimension": "minecraft:overworld",
    "incontrol": "true",
    "result": "deny"
  }
]

**Comment by BurgerPotato** [comment]
Forgot it was that easy, just to add another mod or edit the files, thx for the help people! Imma go test that Incontrol mod

**Comment by Pelargir42** [comment]
Shouldn't have to add a mod for something that should already be in the
configs of the original mod

**Comment by Jeryn99** [comment]
There is, no one edits it

**Comment by Pelargir42** [comment]
I found the config, and it changes the overworld just fine, it seems to
ignore other dimensions though.

I would understand having to add lines for modded dimensions, but not for
the 3 vanilla dimensions.

**Comment by piiiiper** [comment]
love this mod, have been enjoying it thoroughly! ive been having this same issue of having too many weeping angels spawn in the nether, ~20 per minute, despite the limits set in the config. im unable to add the mod suggested as it runs with the forge mod loader, and im using fabric.

do you have an alternative mod in mind for fabric, or any other suggestions? thanks!
