### ISSUE TITLE
1.19.2 angels nor structures are spawning - terralith incompatibility??

### ISSUE THREAD

**Issue by Carnage109** [ReallySub/Weeping-Angels-Mod#319]
I am very inexperienced in the world of modding, so I'm not sure what to do or how to configure the mod, when i go to configure in the mods tab in minecraft it is blacked out and i can't do anything... any advice??? think it could be an incompatibility with terralith maybe

**Comment by Jeryn99** [comment]
Hello. You have supplied the Minecraft Version but you haven't stated whether the loader is Forge or Fabric. Additionally, most mods require a external mod menu mod in order to edit mod configs as Forge did away with theirs. You will need https://www.curseforge.com/minecraft/mc-mods/configured for Forge and a equivalent for Fabric 

Without one of these mods installed, you will need to use your experience to open the config file found in your installations config folder and edit that with notepad or your operating systems equivalent of a text editor

**Comment by Carnage109** [comment]
sorry it was forge, i'll keep you posted on how the configure thing works!

**Comment by Carnage109** [comment]
okay changed the spawn rate from 8 to 200 and nothing still spawns and the closest graveyard is 25,000+ blocks away, and other advice?
