### ISSUE TITLE
Donator Retrieval Causing Freezing and Extended Startup Time

### ISSUE THREAD

**Issue by Monnotone** [ReallySub/Weeping-Angels-Mod#391]
The mod tries strangely hard to retrieve the list of donators, enough to the point where it waits 1-2 minutes between attempts before giving up, and sometimes still will start a new attempt. If the website is down or the mod experiences any other sort of connection issues, the game can take as long as 5 minutes or more to start up. It seems like it will sometimes check again once the game does start up as well, freezing up the menu. Attached are a couple screenshots of the logs; this is also for version 1.19.2-43.1.1-forge.
![image](https://github.com/user-attachments/assets/6b9af6cf-288b-4f27-bfcc-dd72abe97dba)
![image](https://github.com/user-attachments/assets/ca490b34-7217-4af5-b2e3-fd4638c33f50)

**Comment by Jeryn99** [comment]
I’m aware of this, I’ll be fixing it soon

**Comment by Monnotone** [comment]
Got it, good luck. Hopefully you're able to fix it quickly too, since opening this issue my players and I realised it causes freezes in-game too. They last about 15-30 seconds for me but up to 2 or 3 minutes at worst for some other people. We're running a pretty unforgiving pack, so that kind of freezing can be very inconvenient if it occurs in an unsafe environment.

**Comment by Jeryn99** [comment]
The main reason this occurred is because of the following
![image](https://github.com/user-attachments/assets/8281836a-f854-45d4-b0dc-f02a4e4476da)

I would usually never expect my server do go down like this, but I have sent out a fix forge-1.19.2-43.1.2
It will fallback on existing data now, and the logic has been moved off thread so if it cant do anything, you would never know 

https://modrinth.com/mod/weeping-angels/version/forge-1.19.2-43.1.2
https://modrinth.com/mod/weeping-angels/version/fabric-1.19.2-43.1.2

Curse soon, they just take ages to approve!
